language: java

matrix:
  include:
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk12
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk11
    - env:
      - TARGET_AP_SERVER=tomcat90
      - NEED_DEPLOY=true
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomcat85
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomcat70
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomee80
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomee71
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly17
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly13
      jdk: openjdk8
    - env: TARGET_AP_SERVER=liberty-ee8
      jdk: openjdk8
    - env: TARGET_AP_SERVER=liberty-ee7
      jdk: openjdk8
    - env: TARGET_AP_SERVER=jetty
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish5
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish4
      jdk: openjdk8
    - env: TARGET_AP_SERVER=resin
      jdk: openjdk8
  allow_failures:
    # Fail integration test because cannot unpack product zip file of application server
    - env: TARGET_AP_SERVER=wildfly17
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly13
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish5
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish4
      jdk: openjdk8

cache:
  directories:
    - "$HOME/.m2"

before_script:
  - export CARGO_MAVEN_PLUGIN_VERSION=`mvn -B help:evaluate -Dexpression=cargo-maven2-plugin.version | grep -v '^\['`
  - ./mvnw dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_MAVEN_PLUGIN_VERSION}:war -Dmdep.stripVersion=true
  - java -jar ./target/dependency/cargo-daemon-webapp.war &

script:
  - ./mvnw -U clean verify cargo:daemon-start -P ${TARGET_AP_SERVER}
  - ./mvnw -U test -P itest

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
  - secure: OYpjRGu1vnh+yrWqdpaF1nWAzshvlFzh9frQGZv51PCrB+xnwY6SLiwtrlNZ9NKp60Buoxf3YySAml2xG86Y0gUCVjUsFlWg0mBFs1Hvnv6lxUVla6ZjiQ+C9wSavjky6jPbGrBjHd2uXvdUnElMzJc7j6Czm6BigmAaivPfwE0=
  - secure: n8R+jUI2M/SY3pfiVOP95jLbkMXSIrAVhJ6ttTyr9k9OpLdIiP0LJ/Ccv/lNawx0TBlbApcZsc+fh3YZC5QJOl4+2pT9yc7+nULv8LlWoDVjWy+31rD6UJsxgGvADks1gs8SYvW2oHP2vNd8GUpNG6W3hmBkQm80wi6ssAxysZM=
